import 'package:flutter/material.dart';
// import 'package:provider/provider.dart';
// import '../../provider/property_provider.dart';
// import '../../models/property.dart';

class CreatePropertyScreen extends StatefulWidget {
  const CreatePropertyScreen({super.key});

  @override
  _CreatePropertyScreenState createState() => _CreatePropertyScreenState();
}

class _CreatePropertyScreenState extends State<CreatePropertyScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _pricePerNightController = TextEditingController();
  final _addressController = TextEditingController();
  final List<String> _images = []; // Placeholder for image URLs

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _pricePerNightController.dispose();
    _addressController.dispose();
    super.dispose();
  }

  // Future<void> _createProperty() async {
  //   if (_formKey.currentState!.validate()) {
  //     final propertyProvider =
  //         Provider.of<PropertyProvider>(context, listen: false);
  //     final newProperty = Property(
  //       id: '', // ID will be generated by the backend
  //       userId: 'your_user_id', // Replace with actual user ID
  //       name: _nameController.text,
  //       description: _descriptionController.text,
  //       images: _images,
  //       pricePerNight: _pricePerNightController.text,
  //       address: _addressController.text,
  //       created_at: DateTime.now(),
  //       updated_at: DateTime.now(),
  //     );

  //     await propertyProvider
  //         .createProperty(newProperty); // Call the create method
  //     Navigator.pop(context); // Go back to the previous screen
  //   }
  // }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Create Property')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Property Name'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a name' : null,
              ),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Description'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a description' : null,
              ),
              TextFormField(
                controller: _pricePerNightController,
                decoration: const InputDecoration(labelText: 'Price per Night'),
                keyboardType: TextInputType.number,
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a price' : null,
              ),
              TextFormField(
                controller: _addressController,
                decoration: const InputDecoration(labelText: 'Address'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter an address' : null,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {},
                // onPressed: _createProperty,
                child: const Text('Create Property'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
